### ISSUE TITLE
How to get  `source_target.csv` and `user_friend_follower.csv` mentioned by data description?

### ISSUE THREAD

**Issue by chandelures** [GitHubLuCheng/UCD#2]
Hi,
First, thanks for your great work! I want to inquire about the `source_target.csv` and `user_friend_follower.csv`  mentioned by data description. 
I have checked the repository and did not find instructions on how to obtain these files. Could you please provide me with more information on how to obtain them?

> The CU Boulder team also provide the user "follows" and "followed" list in files `Instagram_common_users.zip` and `Instagram_normal_users.zip`.
> Extract the network statistics and detailed network into the following 2 files, and place them in the current folder.
> 
> * `source_target.csv`, 3181 rows including header
> ```csv
> Source,Target
> littlemixofficial,vevo
> ...,...
> ```
> 
> * `user_friend_follower.csv`, 605 rows including header
> ```csv
> user,follows,followed
> surfer_magazine,552490,554
> ...,...
> ```

**Comment by avalanchesiqi** [comment]
Hello @chandelures ,

Thank you for your interests in this project. The used datasets were acquired from the [CU CyberSafety Research Center](http://www.cucybersafety.org/). But I just found their website is down, probably because some lead PIs left CU. The first authors in the cited papers may still have the datasets. Here are their websites and I hope they can help you.

- [Homa Hosseinmardi](https://homahm.github.io/)
- [Rahat Ibn Rafiq](https://rahatibnrafiq.github.io/)

We do have a data copy but we cannot distribute that. However, if you acquire the datasets from the CU team, you can use the [data preprocessing script](https://github.com/GitHubLuCheng/UCD/tree/master/data) we published.

**Comment by chandelures** [comment]
Thank you for your assistance! 
I have acquired the datasets specified in the data description, but I am unable to locate files named `source_target.csv` and `user_friend_follower.csv` within the dataset or any scripts that can generate these files. However, I did find these files in a [previous commit history](https://github.com/GitHubLuCheng/UCD/tree/c9877f1ad7988a09400aa1936ff6801242144410/data).

* `source_target.csv`: https://raw.githubusercontent.com/GitHubLuCheng/UCD/c9877f1ad7988a09400aa1936ff6801242144410/data/source_target.csv
* `user_friend_follower.csv`: https://raw.githubusercontent.com/GitHubLuCheng/UCD/c9877f1ad7988a09400aa1936ff6801242144410/data/user_friend_follower.csv
